Updates - December 2021
iacsecurity/tool-compare pull request #51
Opened 2021-12-28 16:44 UTC by ryderdamen

Updates the README with results from the latest tools.

|     | Checkov | Indeni Cloudrail | Kics | Snyk | Terrascan | Tfsec |
|----|----|----|----|----|----|----|
|Tested Version|2.0.694|1.3.836|1.4.9|1.810.0|1.12.0|0.63.1|

Separates out environment variable checks in `make run-all` before running tools for better first-use experience.

2021-12-28 17:25 UTC, yi2020 commented
@ryderdamen were there no significant changes in tool catch rate? Looks like you only included one change with something Cloudrail caught, but I would expect all tools would improve across a four month gap.

2021-12-29 13:02 UTC, charlesk92 commented
Looks like we are just updating the version of each tool in use by this benchmark and the date. LGTM

2021-12-29 13:02 UTC, charlesk92 approved these changes

2021-12-29 13:05 UTC, kaplanlior commented
Please don't update the information for KICS, we've added many queries between 1.4.1 and 1.4.9 the results in this PR doesn't make sense. Also don't makes sense it's the case for all the tools.

2021-12-29 13:15 UTC, charlesk92 commented
@kaplanlior - glad we have another pair of eyes on this :) Would you be open to creating a branch off of this one, update the results for KICs, and submit a PR?

2021-12-29 18:56 UTC, yi2020 commented
@charlesk92 I agree with @kaplanlior, something doesn't make sense. Either the tools didn't run, or something else broke in the chain here. @ryderdamen can you take a look and see how come no other test cases were updated?

2021-12-29 19:45 UTC, charlesk92 requested changes
See feedback from @kaplanlior and @yi2020. Can't let this branch be merged until we do some form of validation.

2025-08-13 16:48 UTC, closed without merging